Repository akhileshverma92/campusfest, pull requests merged in 2024-10, with the labels that each got.

#18 Improved the hero UI and added animations.
  index.html
  style.css
Labels: documentation, good first issue, hacktoberfest2024, hacktoberfest-accepted, hacktoberfest

#33 Added Dark Mode
  index.html
  script.js
  style.css
Labels: good first issue, hacktoberfest2024, hacktoberfest-accepted, hacktoberfest

#46 improved the UI of the registration form
  index.html
Labels: good first issue, hacktoberfest2024, hacktoberfest-accepted, hacktoberfest

#54 Update index.html
  index.html
Labels: enhancement, good first issue, hacktoberfest2024, hacktoberfest-accepted, hacktoberfest

#53 Modified Registration form and Added Top btn
  index.html
  script.js
Labels: good first issue, hacktoberfest2024, hacktoberfest-accepted, hacktoberfest

#72 Added animation for event's cards
  index.html
Labels: enhancement, good first issue, hacktoberfest2024, hacktoberfest-accepted, hacktoberfest

#75 Added website link to README and improved move to top button
  README.md
  assets/up-arrow.png
  index.html
Labels: good first issue, hacktoberfest2024, hacktoberfest-accepted, hacktoberfest
